spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springDB
    username: root
    password: mypassword
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create